// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdBQRqcZRlk7nw9njNero6B-7cKeijhlY',
    appId: '1:566185460273:web:1bf468fa9bcb41aad30b10',
    messagingSenderId: '566185460273',
    projectId: 'sweetbox-final',
    authDomain: 'sweetbox-final.firebaseapp.com',
    storageBucket: 'sweetbox-final.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrIzbDpHU4HylR83y66Q5FFKRzKkGZT9I',
    appId: '1:566185460273:android:9ec98ac6ba79bdd0d30b10',
    messagingSenderId: '566185460273',
    projectId: 'sweetbox-final',
    storageBucket: 'sweetbox-final.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfhx27Du0ycU1OayHham22zckMLPW9zSE',
    appId: '1:566185460273:ios:07dcb91d1aad2111d30b10',
    messagingSenderId: '566185460273',
    projectId: 'sweetbox-final',
    storageBucket: 'sweetbox-final.firebasestorage.app',
    iosBundleId: 'com.example.sweetBoxFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfhx27Du0ycU1OayHham22zckMLPW9zSE',
    appId: '1:566185460273:ios:07dcb91d1aad2111d30b10',
    messagingSenderId: '566185460273',
    projectId: 'sweetbox-final',
    storageBucket: 'sweetbox-final.firebasestorage.app',
    iosBundleId: 'com.example.sweetBoxFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdBQRqcZRlk7nw9njNero6B-7cKeijhlY',
    appId: '1:566185460273:web:93e32ecc0a11c00ed30b10',
    messagingSenderId: '566185460273',
    projectId: 'sweetbox-final',
    authDomain: 'sweetbox-final.firebaseapp.com',
    storageBucket: 'sweetbox-final.firebasestorage.app',
  );
}
